_wandb:
    value:
        cli_version: 0.25.0
        e:
            uop77i0r0rqga43uf068iy5oimh42g5d:
                args:
                    - --mode
                    - baseline
                    - --model
                    - mlp
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "1021821579264"
                        used: "1001986387968"
                email: chiaruiqi@yahoo.com.sg
                executable: C:\Users\sugar\.conda\envs\genaideepl\python.exe
                git:
                    commit: f9e92601a32ab9b353a161e3fb6282de57497483
                    remote: https://github.com/cheriechia/genAI-deepL-project.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-045b9d4f-2303-85e9-6259-8cacf941a98d
                host: CC
                memory:
                    total: "25480257536"
                os: Windows-11-10.0.26200-SP0
                program: C:\Online Courses\NYP\GenAIandDeepL\genAI-deepL-project\main.py
                python: CPython 3.12.12
                root: C:\Online Courses\NYP\GenAIandDeepL\genAI-deepL-project
                startedAt: "2026-02-17T13:15:34.296061Z"
                writerId: uop77i0r0rqga43uf068iy5oimh42g5d
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 84
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 84
                - 98
            "3":
                - 16
            "4": 3.12.12
            "5": 0.25.0
            "6": 4.57.6
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
        visualize:
            test/confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: test/confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            train/confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: train/confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
batch_size:
    value: 32
dropout:
    value: 0.3
epochs:
    value: 10
hidden_dim1:
    value: 64
hidden_dim2:
    value: 32
learning_rate:
    value: 0.001
model_name:
    value: mlp
