method: bayes

metric:
  name: best_macro_f1
  goal: maximize

parameters:
  model_name:
    value: "cnn"

  epochs: 
    value: 50  

  dropout:
    min: 0.3
    max: 0.5

  freeze_resnet:
    value: false

  batch_size: 
    value: 32

  lr_backbone:
    min: 0.0001
    max: 0.001
    distribution: log_uniform_values

  lr_head:
    min: 0.0005
    max: 0.002
    distribution: log_uniform_values
