_wandb:
    value:
        cli_version: 0.25.0
        e:
            s590idahd0o2gtev6a2zbclbnijq0di4:
                args:
                    - --mode
                    - single
                    - --model
                    - bert
                codePath: main.py
                codePathLocal: main.py
                email: chiaruiqi@yahoo.com.sg
                executable: C:\Users\sugar\.conda\envs\genaideepl\python.exe
                git:
                    commit: f9e92601a32ab9b353a161e3fb6282de57497483
                    remote: https://github.com/cheriechia/genAI-deepL-project.git
                host: CC
                os: Windows-11-10.0.26200-SP0
                program: C:\Online Courses\NYP\GenAIandDeepL\genAI-deepL-project\main.py
                python: CPython 3.12.12
                root: C:\Online Courses\NYP\GenAIandDeepL\genAI-deepL-project
                startedAt: "2026-02-17T12:39:52.372802Z"
                writerId: s590idahd0o2gtev6a2zbclbnijq0di4
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 84
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 84
                - 98
            "3":
                - 16
            "4": 3.12.12
            "5": 0.25.0
            "6": 4.57.6
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
batch_size:
    value: 32
dropout:
    value: 0.5
epochs:
    value: 10
freeze_bert:
    value: true
hidden_dim:
    value: 256
learning_rate:
    value: 2e-05
max_len:
    value: 64
